spring:
  application:
    name: auth-service
  config:
    server-addr: localhost:8848
    import:
      - nacos:auth-service.yaml?refresh=true
      - nacos:school-common.yaml?refresh=true
  cloud:
    nacos:
      serverAddr: localhost:8848
      discovery:
        # 服务注册到 Nacos
        enabled: true
    sentinel:
      transport:
        port: 8718
        dashboard: localhost:8858
      eager: true
