server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import:
      - nacos:gateway-service.yaml?refresh=true
      - nacos:school-common.yaml?refresh=true
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        enabled: true
    sentinel:
      transport:
        port: 8720
        dashboard: 127.0.0.1:8858
      eager: true
