spring:
  application:
    name: business-service
  config:
    import:
      - nacos:business-service.yaml?refresh=true
      - nacos:school-common.yaml?refresh=true
  cloud:
    nacos:
      serverAddr: nacos:8848
      discovery:
        # Nacos
        enabled: true
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel-dashboard:8858
      eager: true
    openfeign:
      sentinel:
        enabled: true