spring:
  application:
    name: class-service
  config:
    import:
      - nacos:class-service.yaml?refresh=true
      - nacos:school-common.yaml?refresh=true
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        enabled: true
    sentinel:
      transport:
        port: 8721
        dashboard: 127.0.0.1:8858
      eager: true
    openfeign:
      sentinel:
        enabled: true