spring:
  application:
    name: teacher-service
  config:
    import:
      - nacos:teacher-service.yaml?refresh=true
      - nacos:school-common.yaml?refresh=true
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        enabled: true
    sentinel:
      transport:
        port: 8724
        dashboard: localhost:8858
      eager: true
    openfeign:
      sentinel:
        enabled: true
